package shopee
import("context";"net/http";"net/url";"strconv")
const OrderDetailOptionalFields="buyer_user_id,buyer_username,item_list,total_amount,currency,order_status,payment_method,create_time,update_time,shipping_carrier,checkout_shipping_carrier,recipient_address,message_to_seller,invoice_data,payment_info"
type OrderSummary struct{OrderSN string `json:"order_sn"`; OrderStatus string `json:"order_status,omitempty"`; UpdateTime int64 `json:"update_time,omitempty"`}
type OrderListResponse struct{More bool `json:"more,omitempty"`; NextCursor string `json:"next_cursor,omitempty"`; OrderList []OrderSummary `json:"order_list"`}
type OrderItem struct{ItemID int64 `json:"item_id"`; ModelID int64 `json:"model_id,omitempty"`; ItemName string `json:"item_name,omitempty"`; ItemSKU string `json:"item_sku,omitempty"`; ModelSKU string `json:"model_sku,omitempty"`; ModelName string `json:"model_name,omitempty"`; ModelQuantityPurchased int `json:"model_quantity_purchased,omitempty"`; ModelDiscountedPrice float64 `json:"model_discounted_price,omitempty"`}
type OrderDetail struct{OrderSN string `json:"order_sn"`; OrderStatus string `json:"order_status,omitempty"`; BuyerUsername string `json:"buyer_username,omitempty"`; TotalAmount float64 `json:"total_amount,omitempty"`; Currency string `json:"currency,omitempty"`; PaymentMethod string `json:"payment_method,omitempty"`; CreateTime int64 `json:"create_time,omitempty"`; UpdateTime int64 `json:"update_time,omitempty"`; ItemList []OrderItem `json:"item_list,omitempty"`; RecipientAddress map[string]any `json:"recipient_address,omitempty"`}
func(c *Client)GetOrderList(ctx context.Context,token,shopID,field string,from,to int64,pageSize int,cursor,status string)(OrderListResponse,error){if pageSize<=0{pageSize=50};q:=url.Values{};q.Set("time_range_field",field);q.Set("time_from",strconv.FormatInt(from,10));q.Set("time_to",strconv.FormatInt(to,10));q.Set("page_size",strconv.Itoa(pageSize));if cursor!=""{q.Set("cursor",cursor)};if status!=""{q.Set("order_status",status)};var out OrderListResponse;err:=c.Do(ctx,Request{Method:http.MethodGet,Path:"/order/get_order_list",AccessToken:token,ShopID:shopID,Query:q},&out);return out,err}
func(c *Client)GetOrderDetail(ctx context.Context,token,shopID string,orderSNs []string)([]OrderDetail,error){q:=url.Values{"order_sn_list":[]string{joinComma(orderSNs)},"response_optional_fields":[]string{OrderDetailOptionalFields}};var out struct{OrderList []OrderDetail `json:"order_list"`};err:=c.Do(ctx,Request{Method:http.MethodGet,Path:"/order/get_order_detail",AccessToken:token,ShopID:shopID,Query:q},&out);return out.OrderList,err}
func joinComma(v []string)string{r:="";for i,s:=range v{if i>0{r+=","};r+=s};return r}
